version: "3.7"

services:
  # membuat container item-db
  item-app:
    # menggunakan image yang sudah di push ke GitHub Packages (Container Registry)
    image: ghcr.io/firmansyahrr/item-app:v1

    # memberikan port mapping 80 dari host untuk dapat mengakses ke dalam port 8080 container
    ports:
      - 80:8080

    # memberikan restart policy agar selalu restart ketika terhenti
    restart: always

    # menambahkan proses untuk memastikan bahwa item-app dijalankan setelah item-db diluncurkan terlebih dahulu
    depends_on:
      - item-db

  # membuat container item-db
  item-db:
    # menggunakan image database mongodb dengan tag 3 dari container registry docker
    image: mongo:3

    # menambahkan informasi volume yang digunakan pada container mongodb
    volumes:
      - app-db:/data/db

    # memberikan restart policy agar selalu restart ketika terhenti
    restart: always

volumes:
  app-db: